# ========================================
# Vault Kubernetes Authentication Setup
# Apply this BEFORE running the main setup script
# ========================================

---
# ServiceAccount for Vault to use when reviewing tokens
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: vault

---
# ClusterRoleBinding grants Vault permission to validate pod tokens
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: vault

---
# ServiceAccounts for each microservice
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: default